ci: minimal-dependencies: Bump nightly version to nightly-2026-03-02
Bump the nightly version used to check minimal dependencies to
`nightly-2026-03-02` to fix an issue with various packages not
supporting the current nightly version `nightly-2025-02-01` (detailed
below).

```
error: rustc 1.86.0-nightly is not supported by the following packages:
  darling@0.23.0 requires rustc 1.88.0
  darling_core@0.23.0 requires rustc 1.88.0
  darling_macro@0.23.0 requires rustc 1.88.0
  instability@0.3.11 requires rustc 1.88
  instability@0.3.11 requires rustc 1.88
  instability@0.3.11 requires rustc 1.88
Either upgrade rustc or select compatible dependency versions with
`cargo update <name>@<current-ver> --precise <compatible-ver>`
where `<compatible-ver>` is the latest version supporting rustc 1.86.0-nightly
```

Signed-off-by: Christopher Obbard <christopher.obbard@linaro.org>