Add context to JWKS file loading error
Currently if the JWKS file is not found, boardswarm provides a generic
error:

    $ boardswarm server.conf
    Error: No such file or directory (os error 2)

This can be unhelpful when determining what caused the error. Add some
context explaining which file failed to load:

    $ boardswarm server.conf
    Error: Failed to load jwks file /etc/boardswarm/auth.jwks

    Caused by:
        No such file or directory (os error 2)

Fixes: #22
Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>