Add context to configuration file loading error
Currently if the configuration file is not found, boardswarm provides a
generic error:

    $ boardswarm null
    Error: No such file or directory (os error 2)

This can be unhelpful when determining what caused the error. Add some
context explaining that the configuration file failed to load:

    $ boardswarm null
    Error: Failed to load configuration file null

    Caused by:
        No such file or directory (os error 2)

Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>