boardswarm-cli: Add context to JSON deserialisation
When passing non-JSON to `boardswarm-cli actuator change-mode`,
boardswarm-cli shows a slightly obscure error message which doesn't
explain that the error is caused by JSON decode:

```
Error: expected value at line 1 column 1
```

Add context to the error message so that the error message is more
self-descriptive:
```
Error: Failed to parse actuator mode as JSON

Caused by:
    expected value at line 1 column 1
```

Also apply the same fix to the console command deserialisation.

Fixes: https://github.com/boardswarm/boardswarm/issues/165
Signed-off-by: Christopher Obbard <christopher.obbard@linaro.org>