cli: Properly handle empty OIDC vector
info.first().unwrap() can happen to be None, e.g. when JWT is intended but
no token is provided:

$ target/debug/boardswarm-cli -i my-boardswarm configure \
	--new --uri http://localhost:6683
thread 'main' panicked at boardswarm-cli/src/main.rs:538:34:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Bail out with appropriate message if the vector turns out empty.

Signed-off-by: Andrzej Pietrasiewicz <andrzej.p@collabora.com>